from typing import Optional

from fastapi import HTTPException, UploadFile

from app.config.credentials_config import config
from app.utils.image_generator import s3_client
import uuid


async def validate_and_read_image_file(file: UploadFile) -> bytes:
    if file.content_type not in ["image/png", "image/jpeg"]:
        raise HTTPException(
            status_code=400,
            detail="Only PNG or JPEG images are allowed",
        )

    file_bytes = await file.read()
    if not file_bytes:
        raise HTTPException(status_code=400, detail="Empty file uploaded")

    return file_bytes


def delete_s3_object_if_exists(existing_logo_url: Optional[str]) -> None:
    prefix = (
        f"https://{config.S3_BUCKET_NAME}.s3."
        f"{config.AWS_REGION}.amazonaws.com/"
    )

    if existing_logo_url and existing_logo_url.startswith(prefix):
        old_key = existing_logo_url[len(prefix):]
        try:
            s3_client.delete_object(
                Bucket=config.S3_BUCKET_NAME,
                Key=old_key,
            )
        except Exception as e:
            # Log but do not fail the whole operation if delete fails
            print(
                "[campaign_helpers] Failed to delete old logo from S3: "
                f"{e}"
            )


async def upload_file_to_s3_with_prefix(
    prefix_folder: str,
    object_id: str,
    file: Optional[UploadFile] = None,
    file_bytes: Optional[bytes] = None,
    filename: Optional[str] = None,
    content_type: Optional[str] = None,
) -> str:
    """
    Generic S3 uploader that supports both UploadFile + bytes and raw
    filename/content_type + bytes.

    Usage patterns:
    - For form uploads:
        await upload_file_to_s3_with_prefix(prefix, object_id, file=file, file_bytes=bytes)
    - For generated bytes:
        await upload_file_to_s3_with_prefix(
            prefix, object_id, filename="brief.pdf",
            content_type="application/pdf", file_bytes=bytes
        )
    """
    if not file_bytes:
        raise HTTPException(status_code=400, detail="Empty file content for S3 upload")

    prefix = (
        f"https://{config.S3_BUCKET_NAME}.s3."
        f"{config.AWS_REGION}.amazonaws.com/"
    )

    # Derive filename / content_type from UploadFile when provided
    if file is not None:
        if not filename:
            filename = file.filename or "upload.bin"
        if not content_type:
            content_type = file.content_type or "application/octet-stream"
    else:
        # Generated bytes path must supply filename and content_type
        if not filename:
            filename = "upload.bin"
        if not content_type:
            content_type = "application/octet-stream"

    extension = filename.split(".")[-1].lower() if "." in filename else "bin"
    unique_id = str(uuid.uuid4())
    s3_key = f"{prefix_folder}/{object_id}_{unique_id}.{extension}"

    try:
        s3_client.put_object(
            Bucket=config.S3_BUCKET_NAME,
            Key=s3_key,
            Body=file_bytes,
            ContentType=content_type,
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"S3 upload failed: {str(e)}")

    return prefix + s3_key