from app.agents.Instagram.graph.instagram_graph import instagram_graph


async def instagram_negotiation_agent(payload: dict) -> str:
    initial_state = {
        "thread_id": payload["thread_id"],
        "user_message": payload["message"],
    }
    print(f"Initial state: {initial_state}")
    result = await instagram_graph.ainvoke(initial_state)
    print(f"Result: {result}")
    final_reply = result.get("final_reply")
    if not final_reply:
        raise ValueError(
            f"No reply generated by agent for thread_id: {payload['thread_id']}"
        )
    return final_reply
