from app.agents.Instagram.graph import instagram_graph
from app.core.exception import InternalServerErrorException


async def instagram_negotiation_agent(payload: dict) -> str:
    initial_state = {
        "thread_id": payload["thread_id"],
        "user_message": payload["message"],
    }
    print(f"Initial state: {initial_state}")
    result = await instagram_graph.ainvoke(initial_state)
    print(f"Result: {result}")
    final_reply = result.get("final_reply")
    if not final_reply:
        raise InternalServerErrorException("No reply generated by agent")

    return final_reply
